/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.View;

import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Car;
import model.Cars;
import ui.Update.UpdatingCarJPanel;

/**
 *
 * @author gaurav
 */
public class ViewJPanelOptions extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanelOptions
     */
    private JPanel userProcessContainer;
    private Cars cars;
    private List<Car> cars1;
    
    
    public ViewJPanelOptions(JPanel upc , Cars c) {
        cars = c;
        userProcessContainer = upc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFirstAvailableCar = new javax.swing.JButton();
        lblViewCars = new javax.swing.JLabel();
        btnTotalNumberOfAvailableCars = new javax.swing.JButton();
        btnListCarsByManufacturer = new javax.swing.JButton();
        btnListCarsByManufactureYear = new javax.swing.JButton();
        btnListCarsBySeatNumbers = new javax.swing.JButton();
        btnListCarBySerialNumber = new javax.swing.JButton();
        btnListCarsByModelNumber = new javax.swing.JButton();
        btnListAllCarManufacturers = new javax.swing.JButton();
        btnLastTimeFleetWasUpdated = new javax.swing.JButton();
        btnListCarsByGivenCity = new javax.swing.JButton();
        btnListCarsExpiredMaintainanceDate = new javax.swing.JButton();

        btnFirstAvailableCar.setText("Find First Available Car");
        btnFirstAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailableCarActionPerformed(evt);
            }
        });

        lblViewCars.setText("VIEW CARS");

        btnTotalNumberOfAvailableCars.setText("Total Number Of Available Cars");
        btnTotalNumberOfAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalNumberOfAvailableCarsActionPerformed(evt);
            }
        });

        btnListCarsByManufacturer.setText("List Cars By Manufacturer");
        btnListCarsByManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsByManufacturerActionPerformed(evt);
            }
        });

        btnListCarsByManufactureYear.setText("List Cars By Manufacture Year");

        btnListCarsBySeatNumbers.setText("List Cars By Seat Numbers");

        btnListCarBySerialNumber.setText("List Car By Serial Number");

        btnListCarsByModelNumber.setText("List Cars By Model Number");

        btnListAllCarManufacturers.setText("List All Car manufacturers");

        btnLastTimeFleetWasUpdated.setText("Last Time Fleet Was Updated");

        btnListCarsByGivenCity.setText("List Cars By Given City");

        btnListCarsExpiredMaintainanceDate.setText("List Cars With Expired Maintainance Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTotalNumberOfAvailableCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFirstAvailableCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByManufactureYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsBySeatNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListCarBySerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListAllCarManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLastTimeFleetWasUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(btnListCarsByGivenCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(lblViewCars))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnListCarsExpiredMaintainanceDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblViewCars)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirstAvailableCar)
                    .addComponent(btnListCarBySerialNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalNumberOfAvailableCars)
                    .addComponent(btnListCarsByModelNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsByManufacturer)
                    .addComponent(btnListAllCarManufacturers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsByManufactureYear)
                    .addComponent(btnLastTimeFleetWasUpdated))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsBySeatNumbers)
                    .addComponent(btnListCarsByGivenCity))
                .addGap(50, 50, 50)
                .addComponent(btnListCarsExpiredMaintainanceDate)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListCarsByManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsByManufacturerActionPerformed
        ListCarsByManufacturersJPanel lcbmjp = new ListCarsByManufacturersJPanel(userProcessContainer, cars);
        userProcessContainer.add("ListCarsByManufacturersJPanel",lcbmjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsByManufacturerActionPerformed

    private void btnFirstAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailableCarActionPerformed
        
        
        try{
        Car c;
        c = cars.searchFirstAvailableCar();
        if(c!=null){
        FindFirstAvailableCarJPanel ffacjp = new FindFirstAvailableCarJPanel(userProcessContainer, c);
        userProcessContainer.add("FindFirstAvailableCarJPanel", ffacjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFirstAvailableCarActionPerformed

    private void btnTotalNumberOfAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalNumberOfAvailableCarsActionPerformed
        try{
        List<Car> c;
        c = cars.getAllCars();
        if(c!=null){
        TotalNoOfCarsAvailable tnoca = new TotalNoOfCarsAvailable(userProcessContainer, c);
        userProcessContainer.add("TotalNoOfCarsAvailable", tnoca);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTotalNumberOfAvailableCarsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstAvailableCar;
    private javax.swing.JButton btnLastTimeFleetWasUpdated;
    private javax.swing.JButton btnListAllCarManufacturers;
    private javax.swing.JButton btnListCarBySerialNumber;
    private javax.swing.JButton btnListCarsByGivenCity;
    private javax.swing.JButton btnListCarsByManufactureYear;
    private javax.swing.JButton btnListCarsByManufacturer;
    private javax.swing.JButton btnListCarsByModelNumber;
    private javax.swing.JButton btnListCarsBySeatNumbers;
    private javax.swing.JButton btnListCarsExpiredMaintainanceDate;
    private javax.swing.JButton btnTotalNumberOfAvailableCars;
    private javax.swing.JLabel lblViewCars;
    // End of variables declaration//GEN-END:variables
}
