/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.View;

import java.awt.CardLayout;
import java.util.Date;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Car;
import model.Cars;
import ui.Update.UpdatingCarJPanel;

/**
 *
 * @author gaurav
 */
public class ViewJPanelOptions extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanelOptions
     */
    private JPanel userProcessContainer;
    private Cars cars;
    private List<Car> cars1;
    
    
    public ViewJPanelOptions(JPanel upc , Cars c) {
        cars = c;
        userProcessContainer = upc;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnFirstAvailableCar = new javax.swing.JButton();
        lblViewCars = new javax.swing.JLabel();
        btnTotalNumberOfAvailableCars = new javax.swing.JButton();
        btnListCarsByManufacturer = new javax.swing.JButton();
        btnListCarsByManufactureYear = new javax.swing.JButton();
        btnListCarsBySeatNumbers = new javax.swing.JButton();
        btnListCarBySerialNumber = new javax.swing.JButton();
        btnListCarsByModelNumber = new javax.swing.JButton();
        btnListAllCarManufacturers = new javax.swing.JButton();
        btnLastTimeFleetWasUpdated = new javax.swing.JButton();
        btnListCarsByGivenCity = new javax.swing.JButton();
        btnListCarsExpiredMaintainanceDate = new javax.swing.JButton();

        btnFirstAvailableCar.setText("Find First Available Car");
        btnFirstAvailableCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstAvailableCarActionPerformed(evt);
            }
        });

        lblViewCars.setText("VIEW CARS");

        btnTotalNumberOfAvailableCars.setText("Total Number Of Available Cars");
        btnTotalNumberOfAvailableCars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalNumberOfAvailableCarsActionPerformed(evt);
            }
        });

        btnListCarsByManufacturer.setText("List Cars By Manufacturer");
        btnListCarsByManufacturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsByManufacturerActionPerformed(evt);
            }
        });

        btnListCarsByManufactureYear.setText("List Cars By Manufacture Year");
        btnListCarsByManufactureYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsByManufactureYearActionPerformed(evt);
            }
        });

        btnListCarsBySeatNumbers.setText("List Cars By Seat Numbers");
        btnListCarsBySeatNumbers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsBySeatNumbersActionPerformed(evt);
            }
        });

        btnListCarBySerialNumber.setText("List Car By Serial Number");
        btnListCarBySerialNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarBySerialNumberActionPerformed(evt);
            }
        });

        btnListCarsByModelNumber.setText("List Cars By Model Number");
        btnListCarsByModelNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsByModelNumberActionPerformed(evt);
            }
        });

        btnListAllCarManufacturers.setText("List All Car manufacturers");
        btnListAllCarManufacturers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListAllCarManufacturersActionPerformed(evt);
            }
        });

        btnLastTimeFleetWasUpdated.setText("Last Time Fleet Was Updated");
        btnLastTimeFleetWasUpdated.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastTimeFleetWasUpdatedActionPerformed(evt);
            }
        });

        btnListCarsByGivenCity.setText("List Cars By Given City");
        btnListCarsByGivenCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsByGivenCityActionPerformed(evt);
            }
        });

        btnListCarsExpiredMaintainanceDate.setText("List Cars With Expired Maintainance Date");
        btnListCarsExpiredMaintainanceDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListCarsExpiredMaintainanceDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTotalNumberOfAvailableCars, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByManufacturer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnFirstAvailableCar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByManufactureYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsBySeatNumbers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnListCarBySerialNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListCarsByModelNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnListAllCarManufacturers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLastTimeFleetWasUpdated, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(btnListCarsByGivenCity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(80, 80, 80))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(365, 365, 365)
                        .addComponent(lblViewCars))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnListCarsExpiredMaintainanceDate)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblViewCars)
                .addGap(83, 83, 83)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirstAvailableCar)
                    .addComponent(btnListCarBySerialNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTotalNumberOfAvailableCars)
                    .addComponent(btnListCarsByModelNumber))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsByManufacturer)
                    .addComponent(btnListAllCarManufacturers))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsByManufactureYear)
                    .addComponent(btnLastTimeFleetWasUpdated))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListCarsBySeatNumbers)
                    .addComponent(btnListCarsByGivenCity))
                .addGap(50, 50, 50)
                .addComponent(btnListCarsExpiredMaintainanceDate)
                .addContainerGap(186, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnListCarsByManufacturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsByManufacturerActionPerformed
        SearchCarsByManufacturersJPanel scbmjp = new SearchCarsByManufacturersJPanel(userProcessContainer, cars);
        userProcessContainer.add("ListCarsByManufacturersJPanel",scbmjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsByManufacturerActionPerformed

    private void btnFirstAvailableCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstAvailableCarActionPerformed
        
        
        try{
        Car c;
        c = cars.searchFirstAvailableCar();
        if(c!=null){
        FindFirstAvailableCarJPanel ffacjp = new FindFirstAvailableCarJPanel(userProcessContainer, c);
        userProcessContainer.add("FindFirstAvailableCarJPanel", ffacjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnFirstAvailableCarActionPerformed

    private void btnTotalNumberOfAvailableCarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalNumberOfAvailableCarsActionPerformed
    try{
        List<Car> c;
        c = cars.getAllAvailableCars();
        if(c.size()>0){
        TotalNoOfCarsAvailable tnoca = new TotalNoOfCarsAvailable(userProcessContainer, c);
        userProcessContainer.add("TotalNoOfCarsAvailable", tnoca);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTotalNumberOfAvailableCarsActionPerformed

    private void btnListCarBySerialNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarBySerialNumberActionPerformed
        SearchCarBySerialNumberJPanel scbsnjp = new SearchCarBySerialNumberJPanel(userProcessContainer, cars);
        userProcessContainer.add("SearchCarBySerialNumberJPanel",scbsnjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarBySerialNumberActionPerformed

    private void btnListCarsByModelNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsByModelNumberActionPerformed
        SearchCarByModelNumberJPanel scbmnjp = new SearchCarByModelNumberJPanel(userProcessContainer, cars);
        userProcessContainer.add("SearchCarByModelNumberJPanel",scbmnjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsByModelNumberActionPerformed

    private void btnListCarsByManufactureYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsByManufactureYearActionPerformed
        SearchCarByManufactureYearJPanel scbmyjp = new SearchCarByManufactureYearJPanel(userProcessContainer, cars);
        userProcessContainer.add("SearchCarByManufactureYearJPanel",scbmyjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsByManufactureYearActionPerformed

    private void btnListCarsBySeatNumbersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsBySeatNumbersActionPerformed
        SearchCarBySeatsJPanel scbsjp = new SearchCarBySeatsJPanel(userProcessContainer, cars);
        userProcessContainer.add("SearchCarBySeatsJPanel",scbsjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsBySeatNumbersActionPerformed

    private void btnListCarsExpiredMaintainanceDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsExpiredMaintainanceDateActionPerformed
    try{
        List<Car> c;
        c = cars.getCarsByExpiredMaintainanceCertificate();
        if(c.size()>0){
        CarsWithExpiredMaintainanceDate cwemd = new CarsWithExpiredMaintainanceDate(userProcessContainer, c);
        userProcessContainer.add("CarsWithExpiredMaintainanceDate", cwemd);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListCarsExpiredMaintainanceDateActionPerformed

    private void btnListCarsByGivenCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListCarsByGivenCityActionPerformed
        SearchCarsByCityJPanel scbcjp = new SearchCarsByCityJPanel(userProcessContainer, cars);
        userProcessContainer.add("SearchCarsByCityJPanel",scbcjp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnListCarsByGivenCityActionPerformed

    private void btnLastTimeFleetWasUpdatedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastTimeFleetWasUpdatedActionPerformed
        try{
        Date date;
        date = cars.getLastUpdateTime();
        if(date!= null){
            System.out.println(date);
            JOptionPane.showMessageDialog(this,
                    date.toString().substring(4,10) + "," + date.toString().substring(24) + " " + date.toString().substring(11,19),
                    "Fleet was last updated at",
                    JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnLastTimeFleetWasUpdatedActionPerformed

    private void btnListAllCarManufacturersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListAllCarManufacturersActionPerformed
        try{
        HashSet<String> manufacturer = new HashSet<>();
        manufacturer = cars.getManufacturers();
        if(!manufacturer.isEmpty()){
        CarsManufacturers cm = new CarsManufacturers(userProcessContainer, manufacturer);
        userProcessContainer.add("CarsManufacturers", cm);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        }
        else{
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
            //return;
        }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Nothing found", "No result found matching your criteria!!", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnListAllCarManufacturersActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFirstAvailableCar;
    private javax.swing.JButton btnLastTimeFleetWasUpdated;
    private javax.swing.JButton btnListAllCarManufacturers;
    private javax.swing.JButton btnListCarBySerialNumber;
    private javax.swing.JButton btnListCarsByGivenCity;
    private javax.swing.JButton btnListCarsByManufactureYear;
    private javax.swing.JButton btnListCarsByManufacturer;
    private javax.swing.JButton btnListCarsByModelNumber;
    private javax.swing.JButton btnListCarsBySeatNumbers;
    private javax.swing.JButton btnListCarsExpiredMaintainanceDate;
    private javax.swing.JButton btnTotalNumberOfAvailableCars;
    private javax.swing.JLabel lblViewCars;
    // End of variables declaration//GEN-END:variables
}
